### ISSUE TITLE
Ability to set executable bit/create symlinks for data files

### ISSUE THREAD

**Issue by snoyberg** [fpco/ide-backend#204]
This is not an urgent issue, filing now after discussing with Duncan.

Our IDE allows users to interact with Git repositories, which support three kinds of blobs: plain, executable, and symlink. Currently, there is no support in the ide-backend API for executables and symlinks. I'd like to have an extension to the API to allow for these two additional types of files.

Note that we do *not* need full access to the POSIX filesystem API. Arbitrary file modes, hard links, empty directories, etc, are *not a requirement at all*. We simply want to emulate Git's capabilities.

Here's [an example repo we'd like to be able to clone](https://github.com/snoyberg/special-file-types), which includes good and bad symlinks, an executable file, and Haskell source code. We can currently reliably clone this into our IDE, but when ide-backend creates its own copies of the datafiles, the symlinks and executable bits are not maintained.

**Comment by mgsloan** [comment]
Now that ide-backend supports a local working dir, I no longer think this is important.
