### ISSUE TITLE
Use a psuedo terminal when running user code

### ISSUE THREAD

**Issue by snoyberg** [fpco/ide-backend#235]
The goal would be to fix the line buffering behavior to match `runghc` or running a compiled executable. This isn't a strict requirement, but would be a nice enhancement. @dcoutts Let's discuss feasibility on Tuesday.

**Comment by mgsloan** [comment]
I implemented this a while back: https://github.com/fpco/ide-backend/commit/e9cdb91fe6ac5c4a436706efe7fd405ec17c6e8d
