### ISSUE TITLE
Limiting stack size does not work for GHC 7.4

### ISSUE THREAD

**Issue by edsko** [fpco/ide-backend#258]
Although we now support `updateRtsOpts` to set the RTS options for the server, limiting the stack size seems to have no effect in ghc 7.4. It works okay for ghc 7.8 however. 

(ghci manages it for 7.4, so there must be a way, but simply starting the server with +RTS -K.. -RTS does not appear to be sufficient.)

**Comment by mgsloan** [comment]
7.4 doesn't really matter for us anymore
