### ISSUE TITLE
GHC 7.10 support

### ISSUE THREAD

**Issue by snoyberg** [fpco/ide-backend#263]
As discussed with @dcoutts. Not urgent, but it would be nice to have support when GHC 7.10 is officially released. At this point, we can drop GHC 7.4 support.

**Comment by ijuma** [comment]
Should this be closed? https://github.com/fpco/ide-backend/commit/97ecc39d89d2e883056145dfbb5771730068c261 seems to imply that it has been implemented.

**Comment by mgsloan** [comment]
Yup, this is implemented!
