### ISSUE TITLE
Getting ide-backend onto Hackage

### ISSUE THREAD

**Issue by snoyberg** [fpco/ide-backend#269]
@edsko Can we work out details of getting the package onto Hackage? I see three points to be addressed:

1. Let's get rid of the binary-ide-backend dep, since we're only officially supporting 7.8 and up. If you're not opposed, I'll go ahead and push a commit.
2. Get experimental merged to master. @chrisdone mentioned that this is the branch that supports ide-backend-client, so we should ideally get it merged over (or, alternatively, we could release from experimental for now).
3. Release Cabal-ide-backend to Hackage. I don't see another option at that front, since our required changes aren't merged upstream yet.

I can do the legwork on this, just wanted to confirm these moves with you.

Side note: I'm planning on getting a Travis build set up, and once on Hackage get ide-backend into Stackage, so we should get regular build failure updates.

**Comment by edsko** [comment]
Feel free. Our changes to Cabal are merged upstream but not yet released to Hackage.

**Comment by snoyberg** [comment]
Is  experimental in a good shape for release?

**Comment by edsko** [comment]
It's okay to merge `experimental` with `master`.

**Comment by snoyberg** [comment]
I'm getting just one test failure:

```
$ ./dist/build/typecheck-dir/typecheck-dir
Copying files from: test/Cabal
to a temporary directory at: /tmp/typecheck-dir.18605

typecheck-dir: user error (invalid argument test/Cabal)
```

This seems to be introduced by 76ad428c71af06c24de47ff9a81101c679794b2f. I'm not sure of the right way forward here.

**Comment by edsko** [comment]
Just disable this test, it's probably bitrotten.

**Comment by snoyberg** [comment]
I should have waited another minute before commenting, I just pushed this commit that fixes the test:

420f3bf

I'm still fine disabling the test instead if you think that's better.

**Comment by snoyberg** [comment]
It seems like the sdist tarballs are somewhat busted. I tried to fix the test cases, but now I realize that there's no other-modules listing in ide-backend-server.cabal, and that the hs-source-dirs: .. trick won't work.

**Comment by chrisdone** [comment]
I anticipate `-dynamic` in ide-backend-server will be a problem: https://github.com/haskell/hackage-server/issues/308

**Comment by mgsloan** [comment]
Considering it's on hackage, seems this has been resolved.
