### ISSUE TITLE
setup instructions: ghc 7.10

### ISSUE THREAD

**Issue by cocreature** [fpco/ide-backend#271]
`setup/SETUP.md` mentions that one should get a patched version of ghc from `git@github.com:fpco/ghc` but that repo does either not exist or is not public.

**Comment by snoyberg** [comment]
Those instructions are out-of-date actually, a custom GHC is no longer necessary (all patches have been merged upstream). Would you be able to send a PR to update the docs?

**Comment by cocreature** [comment]
I can try to do that, but I need to figure out how to get bytestring-trie to work first. I don't want to submit instructions I couldn't reproduce myself.

**Comment by edsko** [comment]
```

**Comment by edsko** [comment]
```
diff -Nur bytestring-trie-0.2.4-orig/src/Data/Trie/Internal.hs bytestring-trie-0.2.4/src/Data/Trie/Internal.hs
--- bytestring-trie-0.2.4-orig/src/Data/Trie/Internal.hs        2015-01-20 13:21:09.000000000 +0000
+++ bytestring-trie-0.2.4/src/Data/Trie/Internal.hs     2015-01-20 13:23:44.000000000 +0000
@@ -73,7 +73,7 @@
 #ifdef APPLICATIVE_IN_BASE
 import Control.Monad       (ap)
 import Control.Applicative (Applicative(..), (<$>))
-import Data.Foldable       (Foldable(..))
+import Data.Foldable       (Foldable(foldMap))
 import Data.Traversable    (Traversable(traverse))
 #endif
```

**Comment by edsko** [comment]
(I've emailed that to the author of `bytestring-trie` on Jan 20, but no reply.)

**Comment by cocreature** [comment]
@edsko Thanks, that did the trick. I was trying to build upon darks head which has some changes regarding ghc 7.10 but didn't want to built for me at all. I'll make a pr to update the setup instructions later, if you want to do it yourself, that's obvously also fine with me.
