### ISSUE TITLE
ide-backend-common broken by text update

### ISSUE THREAD

**Issue by peti** [fpco/ide-backend#281]
Citing from http://hydra.cryp.to/build/884490/log/raw:

~~~~~~~~~~~~
IdeSession/Util.hs:315:10:
    Duplicate instance declarations:
      instance Binary Text -- Defined at IdeSession/Util.hs:315:10
      instance Binary Text -- Defined in ‘Data.Text’
~~~~~~~~~~~~

**Comment by urbanslug** [comment]
Hmmm I just experienced this and was going to post an issue actually. Could a good temporary fix be depending on the previous version of text? I have commented out the Binary instance of Text in `IdeSession/Util.hs` and it built successfully. I want to see what effect this has.

**Comment by snoyberg** [comment]
Thanks, fix pushed and released to Hackage
