### ISSUE TITLE
  Needs co-ordination with Haskell Tooling Infrastructure

### ISSUE THREAD

**Issue by deepfire** [fpco/ide-backend#287]
For details, please see:

https://groups.google.com/forum/#!msg/haskell-cafe/E-Nmi5wnNjk/vwCWlLP0A50J

**Comment by mgsloan** [comment]
I agree with alan's sentiment that we should solve this once and solve it well, rather than having a myriad of tools.  I'm not sure what action we can take on this, though, beyond making ide-backend / stack-ide / related plugins as excellent as possible.
