### ISSUE TITLE
Clients shouldn't need to worry about ide-backend-rts

### ISSUE THREAD

**Issue by jcpetruzza** [fpco/ide-backend#289]
IIUC every client needs to ensure that `ide-backend-server` is called with a package db that contains the corresponding `ide-backend-rts` package. This is arguably an abstraction leak (and one that makes using the `ide-backend` unnecessarily harder).

One alternative that comes to mind would be to embed in the server's binary a tar-gzip'ed package-db containing just its rts, so that when run it will first extract it to a temp directory and then add it as an additional db (I could probably provide a PR for something like this if it makes sense).

**Comment by mgsloan** [comment]
Good point!  Your suggested implementation sounds sensible and feasible.  

I've considered an alternative implementation, where we have an extra RTS module in every project.  But I think this would lead to a lot of special cases in queries, and could also get tricky when it comes to package flags and the like.  So, I prefer your suggested approach.

A PR for this would be a welcome contribution!

**Comment by lukexi** [comment]
:+1: to this : )

**Comment by mgsloan** [comment]
Great stuff!  I've merged it in
