### ISSUE TITLE
Structured error messages

### ISSUE THREAD

**Issue by edsko** [fpco/ide-backend#36]
The error messages we report are currently just strings. Ideally, we'd get more structured error messages, where instead of "Data.ByteString.Internal.ByteString" as a string we get an `IdInfo` (or comparable) that provides us information about bytestring (where was it defined, which package, why is it in scope, etc.). This is related to #35 too -- we don't really want to report "Data.ByteString.Internal.ByteString" at all, but rather "Data.ByteString.ByteString" (see https://haskell.fpcomplete.com/user/snoyberg/random-code-snippets/bad-document-locations for an example).

**Comment by mgsloan** [comment]
Closing out old issues.

FWIW, stack-ide attempts to regexp out some structure: https://github.com/commercialhaskell/stack-ide/blob/master/stack-ide/src/Stack/Ide/AnnotateMessage.hs

I'd much prefer a principled approach where GHC includes the info.  Relevant discussions here:

https://www.reddit.com/r/haskell/comments/3bnpa7/compiler_errors_for_humans/
https://ghc.haskell.org/trac/ghc/ticket/8809#comment:3
